'use client';
import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ThemeProvider from "@/components/ThemeProvider";
// import About from "@/components/About";
// import Projects from "@/components/Projects";
// import Contacts from "@/components/Contacts";
// import Qta from "@/components/Qta";

const outfit = Outfit({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={outfit.className}>
        
        <ThemeProvider attribute="class" defaultTheme="light">
          <Header />
          {children}
          
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
